### ISSUE TITLE
verify SSL causes an exception error

### ISSUE THREAD

**Issue by riklempens** [oversight/httpprobe#3]
**Describe the bug**

when the checkbox `Verify SSL` is set the httpprobe throws an exception upon an invalid certificate.

**To Reproduce**
1. Enable the http probe on a host with an invalid or  self-signed certificate;
2. Enable the `verify SSL` option;
3. Observe the probe throwing an exception.

**Additional context**

Probe exception logging:

```
Traceback (most recent call last):
  File "/code/lib/check/base.py", line 46, in get_data
    data = await cls.run_check(uri, verify_ssl, with_payload, timeout)
  File "/code/lib/check/checkHTTP.py", line 20, in run_check
    async with session.get(uri, ssl=verify_ssl) as response:
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host vcenter.lab.test-technology.nl:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')]
[W 220412 07:06:59 client:201] on_run_check f87bea6ee2fc-f4432302c700 CheckHTTP Check error: ClientConnectorCertificateError: Cannot connect to host vcenter.lab.test-technology.nl:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')]
[E 220412 07:11:46 base:48] HTTP error (uri: https://vcenter.lab.test-technology.nl/): `Cannot connect to host vcenter.lab.test-technology.nl:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')]`
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1050, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1080, in _create_connection_transport
    await waiter
  File "/usr/local/lib/python3.8/asyncio/sslproto.py", line 529, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/local/lib/python3.8/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.8/ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/code/lib/check/base.py", line 46, in get_data
    data = await cls.run_check(uri, verify_ssl, with_payload, timeout)
  File "/code/lib/check/checkHTTP.py", line 20, in run_check
    async with session.get(uri, ssl=verify_ssl) as response:
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host vcenter.lab.test-technology.nl:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')]
[W 220412 07:11:46 client:201] on_run_check f87bea6ee2fc-f4432302c700 CheckHTTP Check error: ClientConnectorCertificateError: Cannot connect to host vcenter.lab.test-technology.nl:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')]
sysadmin@oversight-prod:/etc/oversight$ 
```

**Comment by joente** [comment]
Instead of logging the full exception, I think a errror logging should be sufficient. Note that this might require a change to the `agentcoreclient` lib. 

Also investigate why the Oversight GUI shows the `checkError` as *green* while a checkError exists:
![image (2)](https://user-images.githubusercontent.com/6572730/163134743-1d1a19eb-b19d-499c-89ad-2ac194262236.png)
